uploads = []
outputs = []

[[generated]]
id = "TiwiRtNGhyXk415ERPuAA"
uri = "file://artifacts/elias-portfolio/src/assets/hero-portrait.png"
type = "image"
title = "Developer in black hoodie cap"

[[generated]]
id = "_c5zFgf7DgXEtjW_3ai7N"
uri = "file://artifacts/elias-portfolio/src/assets/about-portrait.png"
type = "image"
title = "Developer different pose"

[[generated]]
id = "8rkwU5VtDek8Bb1p2Zp3B"
uri = "file://artifacts/elias-portfolio/src/assets/project-chertnodes.png"
type = "image"
title = "Minecraft server dashboard dark"

[[generated]]
id = "-Tl-jrAtP08hfjkEELMRE"
uri = "file://artifacts/elias-portfolio/src/assets/project-protectx.png"
type = "image"
title = "Discord anti crash bot green"

[[generated]]
id = "Pe-fvbXbYPhiaPM4LFgz4"
uri = "file://artifacts/elias-portfolio/src/assets/project-kahoot.png"
type = "image"
title = "Kahoot answers yellow"
