import { motion, AnimatePresence } from "framer-motion";
import { Github, Linkedin, Mail, Instagram, MoreVertical, Moon, Sun, Download, Menu, X } from "lucide-react";
import { useState, useEffect, useRef } from "react";
import { Button } from "@/components/ui/button";

import heroRealImg from "@/assets/hero-real.jpeg";
import aboutRealImg from "@/assets/about-real.jpeg";
import logoImg from "@/assets/logo.png";

/* ─── Translations ─────────────────────────────────────────────── */
const translations = {
  EN: {
    nav: ["home", "projects", "skills", "about-me", "contacts"],
    heroTitle: (accent: string) => (
      <>Junior AI Engineer | <span style={{ color: accent }}>Prompt Specialist</span> & <span style={{ color: accent }}>Automation</span></>
    ),
    heroSub: "I'm currently focused on building AI-powered solutions: prompt engineering, workflow automation, and creative content generation using AI tools.",
    heroBtn: "Contact me",
    workingOn: "Currently working on",
    freelance: "Freelance",
    quoteText: '"A person who has held a knife for too long may not know what to do when handed a flower."',
    quoteAuthor: "- Enrel",
    projectsTitle: "projects",
    viewAll: "View all",
    viewBtn: "View",
    project1Title: "Graphic Design",
    project1Desc: "Creative design work using industry-standard tools.",
    project1Tags: ["Photoshop", "Canva", "Illustrator", "Adobe Animate"],
    project2Title: "3D Design",
    project2Desc: "3D modeling and visualization projects.",
    project2Tags: ["Blender 3D", "SketchUp"],
    skillsTitle: "skills",
    langTitle: "Languages",
    langSkills: "Javascript  C++  Python  etc.",
    toolsTitle: "Tools",
    toolsSkills: "VSCode  Linux  Windows  Figma  Android Studio  GitHub  Photoshop  Animate  Illustrator  SketchUp  Blender  etc.",
    othersTitle: "Others",
    othersSkills: "HTML  CSS  EJS  SCSS  etc.",
    aboutTitle: "about-me",
    aboutText: [
      "I'm Eric Santana Siahaan — a creative tech professional transitioning into AI Engineering, with a strong foundation in Graphic Design and Digital Marketing.",
      "My journey in tech started in 2018 after graduating from Vocational High School majoring in Computer and Network Engineering. Since then, I've worn many hats:",
      [
        "Graphic Designer — 10+ years of freelance experience using Adobe Photoshop, CorelDraw, Adobe Animate, SketchUp, and Blender 3D.",
        "Digital Marketing Manager — Managed full digital presence at PT. AMS Global Mandiri (AMS Trans), Sidoarjo, from August 2024 to December 2025.",
        "AI Engineer (Beginner) — Currently self-learning AI prompting, automation, and building practical AI-powered tools using Python.",
      ],
      "What makes me different is the combination: I don't just build — I design and communicate. That means AI solutions I work on are practical, visually clear, and user-friendly.",
      "I'm open to freelance projects, collaborations, and opportunities in AI, automation, or creative tech.",
    ],
    downloadCV: "Download CV",
    generatedBy: "Generated by ChatGPT",
    contactsTitle: "contacts",
    contactsText: "I'm interested in freelance opportunities. However, if you have any other requests or questions, don't hesitate to contact me.",
    messageMe: "Message me here",
    footerTagline: "Junior AI Engineer | Prompt Specialist & Automation",
    copyright: "© Copyright 2026. Made by Eric Santana Siahaan",
    media: "Media",
    darkMode: "Dark Mode",
    lightMode: "Light Mode",
  },
  ID: {
    nav: ["beranda", "proyek", "keahlian", "tentang-saya", "kontak"],
    heroTitle: (accent: string) => (
      <>Junior AI Engineer | <span style={{ color: accent }}>Spesialis Prompt</span> & <span style={{ color: accent }}>Otomasi</span></>
    ),
    heroSub: "Saya saat ini fokus membangun solusi berbasis AI: rekayasa prompt, otomasi alur kerja, dan pembuatan konten kreatif menggunakan alat-alat AI.",
    heroBtn: "Hubungi saya",
    workingOn: "Sedang mengerjakan",
    freelance: "Freelance",
    quoteText: '"Seseorang yang terlalu lama memegang pisau mungkin tidak tahu harus berbuat apa ketika diberi bunga."',
    quoteAuthor: "- Enrel",
    projectsTitle: "proyek",
    viewAll: "Lihat semua",
    viewBtn: "Lihat",
    project1Title: "Desain Grafis",
    project1Desc: "Karya desain kreatif menggunakan alat-alat industri terkemuka.",
    project1Tags: ["Photoshop", "Canva", "Illustrator", "Adobe Animate"],
    project2Title: "Desain 3D",
    project2Desc: "Pemodelan dan visualisasi 3D.",
    project2Tags: ["Blender 3D", "SketchUp"],
    skillsTitle: "keahlian",
    langTitle: "Bahasa",
    langSkills: "Javascript  C++  Python  dll.",
    toolsTitle: "Alat",
    toolsSkills: "VSCode  Linux  Windows  Figma  Android Studio  GitHub  Photoshop  Animate  Illustrator  SketchUp  Blender  dll.",
    othersTitle: "Lainnya",
    othersSkills: "HTML  CSS  EJS  SCSS  dll.",
    aboutTitle: "tentang-saya",
    aboutText: [
      "Saya Eric Santana Siahaan — seorang profesional teknologi kreatif yang bertransisi ke AI Engineering, dengan fondasi kuat di Desain Grafis dan Pemasaran Digital.",
      "Perjalanan saya di bidang teknologi dimulai pada 2018 setelah lulus dari SMK jurusan Teknik Komputer dan Jaringan. Sejak saat itu, saya telah menjalani berbagai peran:",
      [
        "Desainer Grafis — 10+ tahun pengalaman freelance menggunakan Adobe Photoshop, CorelDraw, Adobe Animate, SketchUp, dan Blender 3D.",
        "Manajer Pemasaran Digital — Mengelola kehadiran digital penuh di PT. AMS Global Mandiri (AMS Trans), Sidoarjo, dari Agustus 2024 hingga Desember 2025.",
        "AI Engineer (Pemula) — Saat ini belajar mandiri tentang prompting AI, otomasi, dan membangun alat praktis berbasis AI menggunakan Python.",
      ],
      "Yang membuat saya berbeda adalah kombinasinya: saya tidak hanya membangun — saya juga merancang dan berkomunikasi. Artinya, solusi AI yang saya kerjakan bersifat praktis, jelas secara visual, dan ramah pengguna.",
      "Saya terbuka untuk proyek freelance, kolaborasi, dan peluang di bidang AI, otomasi, atau teknologi kreatif.",
    ],
    downloadCV: "Unduh CV",
    generatedBy: "Dibuat oleh ChatGPT",
    contactsTitle: "kontak",
    contactsText: "Saya tertarik dengan peluang freelance. Namun, jika Anda memiliki permintaan atau pertanyaan lain, jangan ragu untuk menghubungi saya.",
    messageMe: "Hubungi saya di sini",
    footerTagline: "Junior AI Engineer | Spesialis Prompt & Otomasi",
    copyright: "© Hak Cipta 2026. Dibuat oleh Eric Santana Siahaan",
    media: "Media",
    darkMode: "Mode Gelap",
    lightMode: "Mode Terang",
  },
};

/* ─── SVG Icons ─────────────────────────────────────────────────── */
const DiscordIcon = ({ size = 16 }: { size?: number }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="currentColor">
    <path d="M20.317 4.37a19.791 19.791 0 0 0-4.885-1.515.074.074 0 0 0-.079.037c-.21.375-.444.864-.608 1.25a18.27 18.27 0 0 0-5.487 0 12.64 12.64 0 0 0-.617-1.25.077.077 0 0 0-.079-.037A19.736 19.736 0 0 0 3.677 4.37a.07.07 0 0 0-.032.027C.533 9.046-.32 13.58.099 18.057c.001.022.015.043.03.056a19.9 19.9 0 0 0 5.993 3.03.078.078 0 0 0 .084-.028 14.09 14.09 0 0 0 1.226-1.994.076.076 0 0 0-.041-.106 13.107 13.107 0 0 1-1.872-.892.077.077 0 0 1-.008-.128 10.2 10.2 0 0 0 .372-.292.074.074 0 0 1 .077-.01c3.928 1.793 8.18 1.793 12.062 0a.074.074 0 0 1 .078.01c.12.098.246.198.373.292a.077.077 0 0 1-.006.127 12.299 12.299 0 0 1-1.873.892.077.077 0 0 0-.041.107c.36.698.772 1.362 1.225 1.993a.076.076 0 0 0 .084.028 19.839 19.839 0 0 0 6.002-3.03.077.077 0 0 0 .032-.054c.5-5.177-.838-9.674-3.549-13.66a.061.061 0 0 0-.031-.03zM8.02 15.33c-1.183 0-2.157-1.085-2.157-2.419 0-1.333.956-2.419 2.157-2.419 1.21 0 2.176 1.096 2.157 2.42 0 1.333-.956 2.418-2.157 2.418zm7.975 0c-1.183 0-2.157-1.085-2.157-2.419 0-1.333.955-2.419 2.157-2.419 1.21 0 2.176 1.096 2.157 2.42 0 1.333-.946 2.418-2.157 2.418z"/>
  </svg>
);

const WhatsAppIcon = ({ size = 16 }: { size?: number }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="currentColor">
    <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413z"/>
  </svg>
);

const DotsPattern = ({ className = "", color }: { className?: string; color?: string }) => (
  <svg className={className} width="84" height="84" viewBox="0 0 84 84" fill="none">
    {Array.from({ length: 5 }).map((_, row) =>
      Array.from({ length: 5 }).map((_, col) => (
        <circle key={`${row}-${col}`} cx={4 + col * 19} cy={4 + row * 19} r="2" fill={color ?? "currentColor"} opacity="0.3" />
      ))
    )}
  </svg>
);

const GraphicDesignPlaceholder = ({ isDark }: { isDark: boolean }) => (
  <div className="w-full h-full flex items-center justify-center" style={{ background: isDark ? "linear-gradient(135deg, #1a1a2e 0%, #3d1a78 100%)" : "linear-gradient(135deg, #dbeafe 0%, #c7d2fe 100%)" }}>
    <div className="text-center">
      <div className="text-5xl mb-2">🎨</div>
      <div className="text-xs font-mono" style={{ color: isDark ? "#C778DD" : "#1591DC" }}>Graphic Design</div>
    </div>
  </div>
);

const ThreeDPlaceholder = ({ isDark }: { isDark: boolean }) => (
  <div className="w-full h-full flex items-center justify-center" style={{ background: isDark ? "linear-gradient(135deg, #0d1b2a 0%, #1b4332 100%)" : "linear-gradient(135deg, #d1fae5 0%, #a7f3d0 100%)" }}>
    <div className="text-center">
      <div className="text-5xl mb-2">🧊</div>
      <div className="text-xs font-mono" style={{ color: isDark ? "#C778DD" : "#1591DC" }}>3D Design</div>
    </div>
  </div>
);

/* ─── Toggle Switch ─────────────────────────────────────────────── */
const ThemeSwitch = ({ isDark, onToggle, accent }: { isDark: boolean; onToggle: () => void; accent: string }) => (
  <button
    onClick={onToggle}
    className="relative inline-flex items-center w-12 h-6 rounded-full transition-colors duration-300 focus:outline-none"
    style={{ backgroundColor: isDark ? accent : "#ccc" }}
    aria-label="Toggle theme"
  >
    <span
      className="inline-block w-5 h-5 bg-white rounded-full shadow transform transition-transform duration-300"
      style={{ transform: isDark ? "translateX(26px)" : "translateX(2px)" }}
    />
  </button>
);

type Lang = "EN" | "ID";

/* ─── Portfolio ─────────────────────────────────────────────────── */
export default function Portfolio() {
  const [activeSection, setActiveSection] = useState("home");
  const [lang, setLang] = useState<Lang>("EN");
  const [isDark, setIsDark] = useState(true);
  const [kebabOpen, setKebabOpen] = useState(false);
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const kebabRef = useRef<HTMLDivElement>(null);
  const t = translations[lang];
  const navIds = ["home", "projects", "skills", "about-me", "contacts"];

  /* Apply theme CSS variables */
  useEffect(() => {
    const root = document.documentElement;
    if (isDark) {
      root.classList.remove("light-theme");
      root.style.setProperty("--background", "216 12% 18%");
      root.style.setProperty("--foreground", "210 20% 80%");
      root.style.setProperty("--primary", "288 57% 67%");
      root.style.setProperty("--muted-foreground", "210 20% 70%");
      root.style.setProperty("--border", "240 28% 25%");
      root.style.setProperty("--card", "240 28% 16%");
      root.style.setProperty("--card-foreground", "210 20% 80%");
    } else {
      root.classList.add("light-theme");
      root.style.setProperty("--background", "216 30% 97%");
      root.style.setProperty("--foreground", "220 13% 10%");
      root.style.setProperty("--primary", "201 83% 47%");
      root.style.setProperty("--muted-foreground", "220 13% 35%");
      root.style.setProperty("--border", "220 13% 75%");
      root.style.setProperty("--card", "0 0% 100%");
      root.style.setProperty("--card-foreground", "220 13% 10%");
    }
  }, [isDark]);

  /* Close kebab when clicking outside */
  useEffect(() => {
    const handler = (e: MouseEvent) => {
      if (kebabRef.current && !kebabRef.current.contains(e.target as Node)) {
        setKebabOpen(false);
      }
    };
    document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, []);

  /* Lock body scroll when mobile menu is open */
  useEffect(() => {
    document.body.style.overflow = mobileMenuOpen ? "hidden" : "";
    return () => { document.body.style.overflow = ""; };
  }, [mobileMenuOpen]);

  /* Scroll spy */
  useEffect(() => {
    const handleScroll = () => {
      for (const id of navIds) {
        const el = document.getElementById(id);
        if (el) {
          const rect = el.getBoundingClientRect();
          if (rect.top >= -100 && rect.top <= 200) { setActiveSection(id); break; }
        }
      }
    };
    window.addEventListener("scroll", handleScroll, { passive: true });
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  /* Helpers */
  const scrollTo = (id: string) => {
    document.getElementById(id)?.scrollIntoView({ behavior: "smooth" });
    setMobileMenuOpen(false);
  };

  /* ── Theme-derived values ── */
  const pageBg      = isDark ? "#282C33"  : "#F5F7FA";
  const boxBg       = isDark ? "#282C33"  : "#FFFFFF";
  const accentColor = isDark ? "#C778DD"  : "#1591DC";
  const accentGlow  = isDark ? "#C778DD88" : "#1591DC88";
  const headingColor = isDark ? "#ffffff"  : "#1a1a1a";
  const mutedColor   = isDark ? "#ABB2BF"  : "#444444";
  const logoFilter   = isDark
    ? "brightness(0) saturate(100%) invert(59%) sepia(48%) saturate(800%) hue-rotate(250deg) brightness(1.1) drop-shadow(0 0 8px #C778DD)"
    : "brightness(0) saturate(100%) invert(39%) sepia(89%) saturate(600%) hue-rotate(173deg) brightness(1.1) drop-shadow(0 0 8px #1591DC)";
  const cardBg = isDark ? "hsl(240 28% 16%)" : "#ffffff";

  return (
    <div className="min-h-screen font-mono overflow-x-hidden" style={{ backgroundColor: pageBg, color: headingColor }}>

      {/* ── Desktop Sidebar Socials ── */}
      <div className="fixed left-3 top-0 h-full flex-col items-center justify-center gap-4 hidden lg:flex z-40" style={{ color: mutedColor }}>
        <div className="w-px h-24 opacity-30" style={{ backgroundColor: mutedColor }}/>
        <a href="https://github.com/Enrels" target="_blank" rel="noopener noreferrer" className="hover:text-primary transition-colors p-1"><Github size={20}/></a>
        <a href="https://www.linkedin.com/in/eric-santana-siahaan-2199a92b9/" target="_blank" rel="noopener noreferrer" className="hover:text-primary transition-colors p-1"><Linkedin size={20}/></a>
        <a href="mailto:santanixproject@gmail.com" className="hover:text-primary transition-colors p-1"><Mail size={20}/></a>
        <div className="w-px h-24 opacity-30" style={{ backgroundColor: mutedColor }}/>
      </div>

      {/* ── Header ── */}
      <header className="fixed top-0 left-0 right-0 z-50 backdrop-blur-sm border-b border-border/10" style={{ backgroundColor: pageBg + "ee" }}>
        <div className="max-w-5xl mx-auto px-4 sm:px-6 h-16 flex items-center justify-between gap-4">

          {/* Logo */}
          <a href="#home" onClick={() => scrollTo("home")} className="flex items-center gap-2 shrink-0">
            <img src={logoImg} alt="logo" className="h-7 w-auto" style={{ filter: logoFilter }}/>
            <span className="text-base sm:text-lg font-bold" style={{ color: accentColor, textShadow: `0 0 10px ${accentGlow}` }}>
              Eric Santana
            </span>
          </a>

          {/* Desktop nav */}
          <nav className="hidden md:flex items-center gap-4 lg:gap-6">
            {navIds.map((id, i) => (
              <button key={id} onClick={() => scrollTo(id)}
                className="text-sm hover:text-primary transition-colors"
                style={{ color: activeSection === id ? headingColor : mutedColor }}>
                <span style={{ color: accentColor }}>#</span>{t.nav[i]}
              </button>
            ))}

            {/* Lang */}
            <div className="flex items-center gap-1.5 text-sm select-none">
              <span onClick={() => setLang("EN")} className="cursor-pointer hover:text-primary transition-colors px-1 py-0.5"
                style={{ color: lang === "EN" ? headingColor : mutedColor }}>EN</span>
              <span style={{ color: mutedColor, opacity: 0.5 }}>/</span>
              <span onClick={() => setLang("ID")} className="cursor-pointer hover:text-primary transition-colors px-1 py-0.5"
                style={{ color: lang === "ID" ? headingColor : mutedColor }}>ID</span>
            </div>

            {/* Kebab */}
            <div className="relative" ref={kebabRef}>
              <button onClick={() => setKebabOpen(v => !v)}
                className="flex flex-col items-center justify-center gap-[4px] p-2 min-w-[36px] min-h-[36px]"
                aria-label="Theme menu">
                {[0,1,2].map(i => (
                  <span key={i} className="block w-[4px] h-[4px] rounded-full"
                    style={{ backgroundColor: accentColor, boxShadow: `0 0 6px ${accentGlow}` }}/>
                ))}
              </button>
              <AnimatePresence>
                {kebabOpen && (
                  <motion.div initial={{ opacity: 0, scale: 0.9, y: -8 }} animate={{ opacity: 1, scale: 1, y: 0 }}
                    exit={{ opacity: 0, scale: 0.9, y: -8 }} transition={{ duration: 0.15 }}
                    className="absolute right-0 top-11 rounded-md shadow-2xl border border-border z-50 p-4 min-w-[180px]"
                    style={{ backgroundColor: isDark ? "#1e2128" : "#ffffff" }}>
                    <div className="flex items-center justify-between gap-4">
                      <div className="flex items-center gap-2">
                        {isDark ? <Moon size={14} style={{ color: accentColor }}/> : <Sun size={14} style={{ color: accentColor }}/>}
                        <span className="text-sm" style={{ color: mutedColor }}>
                          {isDark ? t.darkMode : t.lightMode}
                        </span>
                      </div>
                      <ThemeSwitch isDark={isDark} onToggle={() => setIsDark(d => !d)} accent={accentColor}/>
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </div>
          </nav>

          {/* Mobile right controls */}
          <div className="flex md:hidden items-center gap-3">
            {/* Lang */}
            <div className="flex items-center gap-1 text-xs select-none">
              <span onClick={() => setLang("EN")} className="cursor-pointer px-1 py-1"
                style={{ color: lang === "EN" ? accentColor : mutedColor }}>EN</span>
              <span style={{ color: mutedColor }}>/</span>
              <span onClick={() => setLang("ID")} className="cursor-pointer px-1 py-1"
                style={{ color: lang === "ID" ? accentColor : mutedColor }}>ID</span>
            </div>
            {/* Hamburger */}
            <button onClick={() => setMobileMenuOpen(v => !v)}
              className="p-2 min-w-[40px] min-h-[40px] flex items-center justify-center"
              aria-label={mobileMenuOpen ? "Close menu" : "Open menu"}
              style={{ color: headingColor }}>
              {mobileMenuOpen ? <X size={22}/> : <Menu size={22}/>}
            </button>
          </div>
        </div>
      </header>

      {/* ── Mobile Full-Screen Menu ── */}
      <AnimatePresence>
        {mobileMenuOpen && (
          <motion.div initial={{ opacity: 0, y: -20 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -20 }}
            transition={{ duration: 0.2 }}
            className="fixed inset-0 z-40 flex flex-col pt-20 px-6 pb-10"
            style={{ backgroundColor: pageBg }}>
            <nav className="flex flex-col gap-5 mt-4">
              {navIds.map((id, i) => (
                <button key={id} onClick={() => scrollTo(id)}
                  className="text-left text-xl font-medium hover:text-primary transition-colors"
                  style={{ color: activeSection === id ? accentColor : headingColor }}>
                  <span style={{ color: accentColor }}>#</span>{t.nav[i]}
                </button>
              ))}
            </nav>

            {/* Theme toggle inside mobile menu */}
            <div className="mt-10 pt-6 border-t flex items-center justify-between" style={{ borderColor: mutedColor + "33" }}>
              <div className="flex items-center gap-2">
                {isDark ? <Moon size={16} style={{ color: accentColor }}/> : <Sun size={16} style={{ color: accentColor }}/>}
                <span className="text-sm" style={{ color: mutedColor }}>
                  {isDark ? t.darkMode : t.lightMode}
                </span>
              </div>
              <ThemeSwitch isDark={isDark} onToggle={() => setIsDark(d => !d)} accent={accentColor}/>
            </div>

            {/* Mobile social links */}
            <div className="mt-6 flex items-center gap-5" style={{ color: mutedColor }}>
              <a href="https://github.com/Enrels" target="_blank" rel="noopener noreferrer" className="hover:text-primary p-1"><Github size={22}/></a>
              <a href="https://www.linkedin.com/in/eric-santana-siahaan-2199a92b9/" target="_blank" rel="noopener noreferrer" className="hover:text-primary p-1"><Linkedin size={22}/></a>
              <a href="mailto:santanixproject@gmail.com" className="hover:text-primary p-1"><Mail size={22}/></a>
              <a href="https://www.instagram.com/enrelacuz/" target="_blank" rel="noopener noreferrer" className="hover:text-primary p-1"><Instagram size={22}/></a>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* ── Main Content ── */}
      <main className="max-w-5xl mx-auto px-4 sm:px-6 pt-24 sm:pt-32 pb-20">

        {/* ── Hero ── */}
        <section id="home" className="min-h-[80vh] flex flex-col md:flex-row items-center justify-between gap-10 py-10">
          <motion.div initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: 0.5 }}
            className="flex-1 space-y-5 text-center md:text-left order-2 md:order-1">
            <h1 className="text-3xl sm:text-4xl md:text-5xl font-semibold leading-tight" style={{ color: headingColor }}>
              {t.heroTitle(accentColor)}
            </h1>
            <p className="text-sm sm:text-base max-w-lg mx-auto md:mx-0" style={{ color: mutedColor }}>{t.heroSub}</p>
            <div className="flex justify-center md:justify-start">
              <Button variant="outline" className="text-sm px-5 py-2 min-h-[44px]"
                style={{ borderColor: accentColor, color: accentColor }}
                onClick={() => scrollTo("contacts")}>
                {t.heroBtn}
              </Button>
            </div>
          </motion.div>

          <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: 0.5, delay: 0.2 }}
            className="flex-1 flex flex-col items-center relative order-1 md:order-2 w-full">
            <img src={heroRealImg} alt="Eric Santana" className="w-full max-w-[320px] sm:max-w-[380px] md:max-w-[400px] object-cover object-top rounded-sm relative z-10"
              style={{ maxHeight: "420px", borderBottom: `1px solid ${accentColor}` }}/>
            <div className="mt-3 p-2 inline-flex items-center gap-2 relative z-10 w-full max-w-[320px] sm:max-w-[380px] md:max-w-[400px]"
              style={{ backgroundColor: pageBg, border: `1px solid ${mutedColor}44` }}>
              <div className="w-3 h-3 shrink-0" style={{ backgroundColor: accentColor }}/>
              <span className="text-xs sm:text-sm" style={{ color: mutedColor }}>
                {t.workingOn} <span style={{ color: headingColor }}>{t.freelance}</span>
              </span>
            </div>
          </motion.div>
        </section>

        {/* ── Quote ── */}
        <section className="py-12 sm:py-20 flex justify-center">
          <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}
            className="relative inline-block w-full max-w-2xl">
            <div className="absolute -top-3 -left-3 text-3xl font-serif" style={{ color: accentColor }}>"</div>
            <div className="p-5 sm:p-6 text-base sm:text-xl" style={{ border: "1px solid #ABB2BF", backgroundColor: boxBg, color: "#ABB2BF" }}>
              {t.quoteText}
            </div>
            <div className="p-3 sm:p-4 text-right" style={{ border: "1px solid #ABB2BF", borderTop: "none", backgroundColor: boxBg, color: "#ABB2BF" }}>
              {t.quoteAuthor}
            </div>
          </motion.div>
        </section>

        {/* ── Projects ── */}
        <section id="projects" className="py-12 sm:py-20">
          <div className="flex flex-wrap items-center justify-between gap-3 mb-8 sm:mb-12">
            <div className="flex items-center gap-3 sm:gap-4">
              <h2 className="text-2xl sm:text-3xl font-medium" style={{ color: headingColor }}>
                <span style={{ color: accentColor }}>#</span>{t.projectsTitle}
              </h2>
              <div className="w-16 sm:w-32 h-px" style={{ backgroundColor: accentColor + "80" }}/>
            </div>
            <a href="#" className="text-sm hover:text-primary transition-colors" style={{ color: headingColor }}>{t.viewAll} →</a>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-5 max-w-2xl">
            {[
              { title: t.project1Title, desc: t.project1Desc, tags: t.project1Tags, placeholder: <GraphicDesignPlaceholder isDark={isDark}/> },
              { title: t.project2Title, desc: t.project2Desc, tags: t.project2Tags, placeholder: <ThreeDPlaceholder isDark={isDark}/> },
            ].map((project, i) => (
              <motion.div key={project.title} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }} transition={{ delay: i * 0.1 }}
                className="flex flex-col" style={{ border: `1px solid ${mutedColor}55`, backgroundColor: cardBg }}>
                <div className="aspect-video overflow-hidden" style={{ borderBottom: `1px solid ${mutedColor}55` }}>
                  {project.placeholder}
                </div>
                <div className="p-3 text-xs sm:text-sm" style={{ borderBottom: `1px solid ${mutedColor}55`, color: mutedColor }}>
                  {project.tags.join("  ")}
                </div>
                <div className="p-4 flex-1 flex flex-col">
                  <h3 className="text-lg sm:text-xl font-medium mb-2" style={{ color: headingColor }}>{project.title}</h3>
                  <p className="text-sm mb-4 flex-1" style={{ color: mutedColor }}>{project.desc}</p>
                  <Button variant="outline" className="rounded-none h-9 px-4 w-fit text-sm min-h-[44px]"
                    style={{ borderColor: accentColor, color: headingColor }}>
                    {t.viewBtn} →
                  </Button>
                </div>
              </motion.div>
            ))}
          </div>
        </section>

        {/* ── Skills ── */}
        <section id="skills" className="py-12 sm:py-20">
          <div className="flex items-center gap-3 sm:gap-4 mb-6 sm:mb-8">
            <h2 className="text-2xl sm:text-3xl font-medium" style={{ color: headingColor }}>
              <span style={{ color: accentColor }}>#</span>{t.skillsTitle}
            </h2>
            <div className="w-16 sm:w-32 h-px" style={{ backgroundColor: accentColor + "80" }}/>
          </div>
          <div className="flex flex-wrap gap-3 sm:gap-4">
            {[
              { title: t.langTitle,   skills: t.langSkills },
              { title: t.toolsTitle,  skills: t.toolsSkills },
              { title: t.othersTitle, skills: t.othersSkills },
            ].map((cat, i) => (
              <motion.div key={cat.title} initial={{ opacity: 0, scale: 0.9 }} whileInView={{ opacity: 1, scale: 1 }}
                viewport={{ once: true }} transition={{ delay: i * 0.1 }}
                className="flex-1 min-w-[150px] max-w-[280px]"
                style={{ border: "1px solid #ABB2BF", backgroundColor: boxBg }}>
                <div className="p-2 font-medium text-sm" style={{ borderBottom: "1px solid #ABB2BF", color: "#ABB2BF" }}>{cat.title}</div>
                <div className="p-2 text-xs sm:text-sm leading-relaxed" style={{ color: "#ABB2BF" }}>{cat.skills}</div>
              </motion.div>
            ))}
          </div>
        </section>

        {/* ── About Me ── */}
        <section id="about-me" className="py-12 sm:py-20">
          <div className="flex items-center gap-3 sm:gap-4 mb-8 sm:mb-12">
            <h2 className="text-2xl sm:text-3xl font-medium" style={{ color: headingColor }}>
              <span style={{ color: accentColor }}>#</span>{t.aboutTitle}
            </h2>
            <div className="w-24 sm:w-64 h-px" style={{ backgroundColor: accentColor + "80" }}/>
          </div>
          <div className="flex flex-col md:flex-row gap-10 sm:gap-12 items-start">
            <motion.div initial={{ opacity: 0, x: -20 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }}
              className="flex-1 space-y-4 order-2 md:order-1">
              {t.aboutText.map((block, i) =>
                Array.isArray(block) ? (
                  <ul key={i} className="space-y-2 pl-1">
                    {block.map((item, j) => (
                      <li key={j} className="flex gap-2 text-sm sm:text-base" style={{ color: mutedColor }}>
                        <span style={{ color: accentColor }} className="shrink-0 mt-0.5">\</span>
                        <span>{item}</span>
                      </li>
                    ))}
                  </ul>
                ) : (
                  <p key={i} className="text-sm sm:text-base" style={{ color: mutedColor }}>{block}</p>
                )
              )}
            </motion.div>

            <motion.div initial={{ opacity: 0, x: 20 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }}
              className="flex-1 flex justify-center order-1 md:order-2 w-full">
              <div className="flex flex-col items-center">
                <img src={aboutRealImg} alt="Eric Santana" className="w-full max-w-[280px] sm:max-w-[320px] object-cover rounded-sm"
                  style={{ maxHeight: "400px", objectPosition: "top", borderBottom: `1px solid ${accentColor}` }}/>
                <p className="mt-3 text-xs font-mono" style={{ color: accentColor }}>{t.generatedBy}</p>
                <a href="/cv.pdf" download="CV_Eric_Santana_Siahaan.pdf" target="_blank" rel="noopener noreferrer"
                  className="mt-4 inline-flex items-center gap-2 px-5 py-2.5 text-sm font-mono transition-opacity hover:opacity-80 min-h-[44px]"
                  style={{ border: `1px solid ${accentColor}`, color: accentColor, backgroundColor: "transparent" }}>
                  <Download size={14}/>
                  {t.downloadCV}
                </a>
              </div>
            </motion.div>
          </div>
        </section>

        {/* ── Contacts ── */}
        <section id="contacts" className="py-12 sm:py-20">
          <div className="flex items-center gap-3 sm:gap-4 mb-8 sm:mb-12">
            <h2 className="text-2xl sm:text-3xl font-medium" style={{ color: headingColor }}>
              <span style={{ color: accentColor }}>#</span>{t.contactsTitle}
            </h2>
            <div className="w-16 sm:w-32 h-px" style={{ backgroundColor: accentColor + "80" }}/>
          </div>
          <div className="flex flex-col gap-8 items-start">
            <motion.p initial={{ opacity: 0 }} whileInView={{ opacity: 1 }} viewport={{ once: true }}
              className="max-w-md text-sm sm:text-base" style={{ color: mutedColor }}>
              {t.contactsText}
            </motion.p>
            <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}
              className="p-5 sm:p-6 w-full max-w-sm"
              style={{ border: `1px solid ${mutedColor}55`, backgroundColor: cardBg }}>
              <h3 className="font-medium mb-5 text-base sm:text-lg" style={{ color: headingColor }}>{t.messageMe}</h3>
              <div className="space-y-4 text-sm">
                <a href="https://wa.me/6287840105200" target="_blank" rel="noopener noreferrer"
                  className="flex items-center gap-3 hover:text-primary transition-colors min-h-[40px]" style={{ color: mutedColor }}>
                  <span style={{ color: accentColor }}><WhatsAppIcon size={16}/></span>+62 878-4010-5200 (ID)
                </a>
                <a href="mailto:santanixproject@gmail.com"
                  className="flex items-center gap-3 hover:text-primary transition-colors min-h-[40px]" style={{ color: mutedColor }}>
                  <Mail size={16} style={{ color: accentColor }}/>santanixproject@gmail.com
                </a>
                <div className="flex items-center gap-3 min-h-[40px]" style={{ color: mutedColor }}>
                  <span style={{ color: accentColor }}><DiscordIcon size={16}/></span>Enrel#6886
                </div>
                <a href="https://www.instagram.com/enrelacuz/" target="_blank" rel="noopener noreferrer"
                  className="flex items-center gap-3 hover:text-primary transition-colors min-h-[40px]" style={{ color: mutedColor }}>
                  <Instagram size={16} style={{ color: accentColor }}/>@enrelacuz
                </a>
              </div>
            </motion.div>
          </div>
        </section>
      </main>

      {/* ── Footer ── */}
      <footer className="border-t py-8 sm:py-10" style={{ borderColor: mutedColor + "33", backgroundColor: pageBg }}>
        <div className="max-w-5xl mx-auto px-4 sm:px-6 flex flex-col sm:flex-row justify-between items-start gap-8">
          <div>
            <div className="flex items-center gap-2 mb-3">
              <img src={logoImg} alt="Eric Santana" className="h-6 w-auto" style={{ filter: logoFilter }}/>
              <span className="text-lg font-bold" style={{ color: accentColor, textShadow: `0 0 10px ${accentGlow}` }}>Eric Santana</span>
            </div>
            <a href="mailto:santanixproject@gmail.com" className="text-xs sm:text-sm block mb-2 hover:text-primary transition-colors" style={{ color: mutedColor }}>
              santanixproject@gmail.com
            </a>
            <p className="text-xs sm:text-sm" style={{ color: mutedColor }}>{t.footerTagline}</p>
          </div>
          <div>
            <h3 className="text-lg font-medium mb-4" style={{ color: headingColor }}>{t.media}</h3>
            <div className="flex items-center gap-4" style={{ color: mutedColor }}>
              <a href="https://github.com/Enrels" target="_blank" rel="noopener noreferrer" className="hover:text-primary transition-colors p-1"><Github size={20}/></a>
              <a href="https://wa.me/6287840105200" target="_blank" rel="noopener noreferrer" className="hover:text-primary transition-colors p-1"><WhatsAppIcon size={20}/></a>
              <a href="https://www.linkedin.com/in/eric-santana-siahaan-2199a92b9/" target="_blank" rel="noopener noreferrer" className="hover:text-primary transition-colors p-1"><Linkedin size={20}/></a>
              <a href="https://discord.com/users/Enrel" target="_blank" rel="noopener noreferrer" className="hover:text-primary transition-colors p-1"><DiscordIcon size={20}/></a>
              <a href="https://www.instagram.com/enrelacuz/" target="_blank" rel="noopener noreferrer" className="hover:text-primary transition-colors p-1"><Instagram size={20}/></a>
            </div>
          </div>
        </div>
        <div className="text-center text-xs sm:text-sm mt-10" style={{ color: accentColor, textShadow: `0 0 8px ${accentGlow}` }}>
          {t.copyright}
        </div>
      </footer>
    </div>
  );
}
